" Name:         Starry Night
" Description:  A dark Vim/Neovim colorscheme with rich colors on a deep black background.
" Author:       Jose Gamez <https://github.com/josegamez82>
" Maintainer:   Jose Gamez <https://github.com/josegamez82>
" Website:      https://github.com/josegamez82/StarryNight
" License:      Vim License (see `:help license`)
" Last Updated: 9/4/2020 6:26:48 PM

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'starrynight'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Boolean Constant
hi! link Character Constant
hi! link Debug Special
hi! link Delimiter Special
hi! link Float Constant
hi! link Function Identifier
hi! link Keyword Statement
hi! link Label Statement
hi! link Number Constant
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Folded
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#393939', '#AB3C2A', '#FFCC66', '#62B85A',
        \ '#6699CC', '#42908E', '#8C629A', '#D3D0C8', '#787878', '#AB3C2A',
        \ '#FFCC66', '#62B85A', '#6699CC', '#42908E', '#8C629A', '#A5A6A4']
  if has('nvim')
    let g:terminal_color_0 = '#393939'
    let g:terminal_color_1 = '#AB3C2A'
    let g:terminal_color_2 = '#FFCC66'
    let g:terminal_color_3 = '#62B85A'
    let g:terminal_color_4 = '#6699CC'
    let g:terminal_color_5 = '#42908E'
    let g:terminal_color_6 = '#8C629A'
    let g:terminal_color_7 = '#D3D0C8'
    let g:terminal_color_8 = '#787878'
    let g:terminal_color_9 = '#AB3C2A'
    let g:terminal_color_10 = '#FFCC66'
    let g:terminal_color_11 = '#62B85A'
    let g:terminal_color_12 = '#6699CC'
    let g:terminal_color_13 = '#42908E'
    let g:terminal_color_14 = '#8C629A'
    let g:terminal_color_15 = '#A5A6A4'
  endif
  if get(g:, 'sn_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#D3D0C8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#D3D0C8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#D3D0C8 guibg=#101010 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#D3D0C8 guibg=#101010 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#263840 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#6699CC guibg=#101010 guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#FFCC66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#000000 guibg=#D3D0C8 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#263840 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#6699CC guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#FFCC66 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#787878 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#42908E guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#6699CC guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#D3D0C8 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#FF5C57 guibg=#101010 guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#AB3C2A guibg=#101010 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#8C629A guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#A5A6A4 guibg=#244F4E guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#42908E guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#000000 guibg=#FF5C57 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#787878 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#000000 guibg=#787878 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#FFCC66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#FFCC66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#FFCC66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#D3D0C8 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#263840 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#000000 guibg=#678CB1 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#393939 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#000000 guibg=#678CB1 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#787878 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#FF5C57 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#6699CC gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#8C629A gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#42908E gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#101010 guibg=#787878 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#D3D0C8 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#D3D0C8 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#101010 guibg=#787878 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#101010 guibg=#A5A6A4 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#393939 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#2F6194 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#42908E guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#42908E guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#D3D0C8 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#62B85A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#101010 guibg=#42908E guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#6699CC guibg=#101010 guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#8C629A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#8C629A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#AB3C2A guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#42908E guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#787878 guibg=#000000 guisp=NONE gui=bold cterm=bold
  hi cOperator guifg=#8C629A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cStatement guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csClass guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csAttribute guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csModifier guifg=#62B85A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csType guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csUnspecifiedStatement guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csContextualStatement guifg=#8C629A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csNewDecleration guifg=#42908E guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csConditional guifg=#8C629A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csSummary guifg=#42908E guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csXmlTag guifg=#FFCC66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyBracket guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyFile guifg=#D3D0C8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyFooter guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyHeader guifg=#2F6194 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyNumber guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyPath guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySection guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySelect guifg=#263840 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySlash guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySpecial guifg=#A5A6A4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerBookmarkExpandIcon guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerBufferExpandIcon guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerFileExpandIcon guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerBookmarkRoot guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerBufferRoot guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerFileRoot guifg=#AB3C2A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerIndentLine guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerBufferNameVisible guifg=#A5A6A4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerBufferBufnr guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerFileRootName guifg=#62B85A guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerFileDirectory guifg=#787878 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerFileDirectoryCollapsed guifg=#6699CC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocExplorerFileDirectoryExpanded guifg=#FFCC66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'sn_transp_bg', 0)
    hi Normal ctermfg=7 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=7 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=7 ctermbg=232 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=7 ctermbg=232 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=6 cterm=NONE
  hi Conceal ctermfg=110 ctermbg=232 cterm=NONE
  hi Conditional ctermfg=221 ctermbg=NONE cterm=NONE
  hi Cursor ctermbg=7 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=6 cterm=NONE
  hi CursorLineNr ctermfg=110 cterm=NONE
  hi Define ctermfg=110 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=221 ctermbg=237 cterm=NONE
  hi DiffChange ctermfg=243 ctermbg=237 cterm=NONE
  hi DiffDelete ctermfg=30 ctermbg=237 cterm=NONE
  hi DiffText ctermfg=110 ctermbg=237 cterm=NONE
  hi Directory ctermfg=243 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=7 cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=232 cterm=NONE
  hi Exception ctermfg=124 ctermbg=232 cterm=NONE
  hi FoldColumn ctermfg=97 ctermbg=237 cterm=NONE
  hi Folded ctermfg=8 ctermbg=23 cterm=NONE
  hi Include ctermfg=30 ctermbg=NONE cterm=NONE
  hi IncSearch ctermbg=203 cterm=NONE
  hi LineNr ctermfg=243 cterm=NONE
  hi Macro ctermfg=124 ctermbg=NONE cterm=NONE
  hi MatchParen ctermbg=243 cterm=NONE
  hi ModeMsg ctermfg=221 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=221 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=243 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=221 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=7 ctermbg=237 cterm=NONE
  hi PmenuSbar ctermfg=6 cterm=NONE
  hi PmenuSel ctermbg=67 cterm=NONE
  hi PmenuThumb ctermfg=237 cterm=NONE
  hi Question ctermfg=110 ctermbg=NONE cterm=NONE
  hi Search ctermbg=67 cterm=NONE
  hi SignColumn ctermfg=243 ctermbg=237 cterm=NONE
  hi SpecialKey ctermfg=243 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=232 ctermbg=243 cterm=NONE
  hi StatusLineNC ctermfg=7 ctermbg=237 cterm=NONE
  hi TabLine ctermfg=7 ctermbg=237 cterm=NONE
  hi TabLineSel ctermfg=232 ctermbg=243 cterm=NONE
  hi TabLineFill ctermfg=232 ctermbg=8 cterm=NONE
  hi Title ctermfg=110 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=237 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=25 cterm=NONE
  hi VisualNOS ctermfg=30 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=30 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=7 ctermbg=237 cterm=NONE
  hi Comment ctermfg=243 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=34 ctermbg=NONE cterm=NONE
  hi Error ctermfg=232 ctermbg=30 cterm=NONE
  hi Identifier ctermfg=110 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=110 ctermbg=232 cterm=NONE
  hi PreProc ctermfg=97 ctermbg=NONE cterm=NONE
  hi Special ctermfg=97 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=110 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=124 ctermbg=237 cterm=NONE
  hi Type ctermfg=124 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=30 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE cterm=NONE
  hi ToolbarButton ctermfg=243 cterm=bold
  hi cOperator ctermfg=97 ctermbg=NONE cterm=NONE
  hi cStatement ctermfg=110 ctermbg=NONE cterm=NONE
  hi csClass ctermfg=124 ctermbg=NONE cterm=NONE
  hi csAttribute ctermfg=124 ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=34 ctermbg=NONE cterm=NONE
  hi csType ctermfg=124 ctermbg=NONE cterm=NONE
  hi csUnspecifiedStatement ctermfg=110 ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=97 ctermbg=NONE cterm=NONE
  hi csNewDecleration ctermfg=30 ctermbg=NONE cterm=NONE
  hi csConditional ctermfg=97 ctermbg=NONE cterm=NONE
  hi csSummary ctermfg=30 ctermbg=NONE cterm=NONE
  hi csXmlTag ctermfg=221 ctermbg=NONE cterm=NONE
  hi StartifyBracket ctermfg=110 ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=7 ctermbg=NONE cterm=NONE
  hi StartifyFooter ctermfg=243 ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=25 ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=110 ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=243 ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=124 ctermbg=NONE cterm=NONE
  hi StartifySelect ctermfg=6 ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=243 ctermbg=NONE cterm=NONE
  hi StartifySpecial ctermfg=8 ctermbg=NONE cterm=NONE
  hi CocExplorerBookmarkExpandIcon ctermfg=124 ctermbg=NONE cterm=NONE
  hi CocExplorerBufferExpandIcon ctermfg=124 ctermbg=NONE cterm=NONE
  hi CocExplorerFileExpandIcon ctermfg=124 ctermbg=NONE cterm=NONE
  hi CocExplorerBookmarkRoot ctermfg=124 ctermbg=NONE cterm=NONE
  hi CocExplorerBufferRoot ctermfg=124 ctermbg=NONE cterm=NONE
  hi CocExplorerFileRoot ctermfg=124 ctermbg=NONE cterm=NONE
  hi CocExplorerIndentLine ctermfg=110 ctermbg=NONE cterm=NONE
  hi CocExplorerBufferNameVisible ctermfg=8 ctermbg=NONE cterm=NONE
  hi CocExplorerBufferBufnr ctermfg=110 ctermbg=NONE cterm=NONE
  hi CocExplorerFileRootName ctermfg=34 ctermbg=NONE cterm=NONE
  hi CocExplorerFileDirectory ctermfg=243 ctermbg=NONE cterm=NONE
  hi CocExplorerFileDirectoryCollapsed ctermfg=110 ctermbg=NONE cterm=NONE
  hi CocExplorerFileDirectoryExpanded ctermfg=221 ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'sn_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=DarkGrey cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=White ctermbg=DarkGrey cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkCyan cterm=NONE
  hi Conceal ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi Conditional ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Black ctermbg=White cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkCyan cterm=NONE
  hi CursorLineNr ctermfg=Blue ctermbg=Black cterm=NONE
  hi Define ctermfg=Blue ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=LightYellow ctermbg=Grey cterm=NONE
  hi DiffChange ctermfg=Grey ctermbg=Grey cterm=NONE
  hi DiffDelete ctermfg=Cyan ctermbg=Grey cterm=NONE
  hi DiffText ctermfg=Blue ctermbg=Grey cterm=NONE
  hi Directory ctermfg=Grey ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=LightRed ctermbg=DarkGrey cterm=NONE
  hi Exception ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi FoldColumn ctermfg=Magenta ctermbg=Grey cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Cyan cterm=NONE
  hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=Black ctermbg=LightRed cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=Black cterm=NONE
  hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=Black ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Operator ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=DarkCyan ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=LightBlue cterm=NONE
  hi PmenuThumb ctermfg=Grey ctermbg=Black cterm=NONE
  hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Search ctermfg=Black ctermbg=LightBlue cterm=NONE
  hi SignColumn ctermfg=Grey ctermbg=Grey cterm=NONE
  hi SpecialKey ctermfg=Grey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=DarkGrey ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Grey cterm=NONE
  hi TabLine ctermfg=White ctermbg=Grey cterm=NONE
  hi TabLineSel ctermfg=DarkGrey ctermbg=Grey cterm=NONE
  hi TabLineFill ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
  hi Title ctermfg=Blue ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi VisualNOS ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=White ctermbg=Grey cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Green ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkGrey ctermbg=Cyan cterm=NONE
  hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi PreProc ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Red ctermbg=Grey cterm=NONE
  hi Type ctermfg=Red ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=Grey ctermbg=Black cterm=bold
  hi cOperator ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi cStatement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi csClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi csAttribute ctermfg=Red ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi csType ctermfg=Red ctermbg=NONE cterm=NONE
  hi csUnspecifiedStatement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csNewDecleration ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi csConditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csSummary ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi csXmlTag ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi StartifyBracket ctermfg=Blue ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=White ctermbg=NONE cterm=NONE
  hi StartifyFooter ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=Blue ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=Red ctermbg=NONE cterm=NONE
  hi StartifySelect ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifySpecial ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi CocExplorerBookmarkExpandIcon ctermfg=Red ctermbg=NONE cterm=NONE
  hi CocExplorerBufferExpandIcon ctermfg=Red ctermbg=NONE cterm=NONE
  hi CocExplorerFileExpandIcon ctermfg=Red ctermbg=NONE cterm=NONE
  hi CocExplorerBookmarkRoot ctermfg=Red ctermbg=NONE cterm=NONE
  hi CocExplorerBufferRoot ctermfg=Red ctermbg=NONE cterm=NONE
  hi CocExplorerFileRoot ctermfg=Red ctermbg=NONE cterm=NONE
  hi CocExplorerIndentLine ctermfg=Blue ctermbg=NONE cterm=NONE
  hi CocExplorerBufferNameVisible ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi CocExplorerBufferBufnr ctermfg=Blue ctermbg=NONE cterm=NONE
  hi CocExplorerFileRootName ctermfg=Green ctermbg=NONE cterm=NONE
  hi CocExplorerFileDirectory ctermfg=Grey ctermbg=NONE cterm=NONE
  hi CocExplorerFileDirectoryCollapsed ctermfg=Blue ctermbg=NONE cterm=NONE
  hi CocExplorerFileDirectoryExpanded ctermfg=LightYellow ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #000000                   0         Black
" Color: deepBlack     #101010                   232       DarkGrey
" Color: deepGrey      #393939                   237       Grey
" Color: blueGrey      #263840                   6         DarkCyan
" Color: darkGrey      #787878                   243       Grey
" Color: grey          #A5A6A4                   8         LightGrey
" Color: creamyGrey    #D3D0C8                   7         White
" Color: lightBlue     #678CB1                   67        LightBlue
" Color: deepBlue      #2F6194                   25        DarkBlue
" Color: deepCyan      #244F4E                   23        Cyan
" Color: darkCyan      #42908E                   30        Cyan
" Color: indianRed     #FF5C57                   203       LightRed
" Color: brightRed     #AB3C2A                   124       Red
" Color: brightYellow  #FFCC66                   221       LightYellow
" Color: brightGreen   #62B85A                   34        Green
" Color: brightBlue    #6699CC                   110       Blue
" Color: brightPurple  #8C629A                   97        Magenta
" Term colors: deepGrey brightRed brightYellow brightGreen
" Term colors: brightBlue darkCyan brightPurple creamyGrey
" Term colors: darkGrey brightRed brightYellow brightGreen
" Term colors: brightBlue darkCyan brightPurple grey
" vim: et ts=2 sw=2
